# === GENERAL SETTINGS ===
MODE = "LIVE"  # LIVE or TEST
SCAN_INTERVAL = 180  # Default scan cycle in seconds (3 min)

# === API KEYS ===
BYBIT_API_URL = "https://api.bybit.com"
BYBIT_API_KEY = "tL7vmTEDT5B8mp4Yer"
BYBIT_API_SECRET = "xH5S3U3dkLeQJ739cl9AZ0MMNQkerD53vAXN"
TELEGRAM_BOT_TOKEN = "7803544014:AAGLJVwfTg4Ij5lzI8RIVRfrZkKG9uIZnh4"
TELEGRAM_CHAT_ID = "1806610681"
ASSISTANT_CHAT_ID = "your_private_assistant_chat_id"  # Optional: for behind-the-scenes logs

# === STRATEGY MODE TOGGLES ===
ENABLE_SCALP = True
ENABLE_INTRADAY = True
ENABLE_SWING = True
ENABLE_SPOT_TRADING = True

# === TIMEFRAMES USED ===
TIMEFRAMES = ['5m', '15m', '1h']
ENABLED_TIMEFRAMES = ["5m", "15m", "1h"]

# === RISK SETTINGS ===
DEFAULT_RISK = 0.03  # 3% per trade
MEME_COIN_RISK = 0.02
SWING_RISK = 0.015
DAILY_MAX_LOSS = 0.10
STOP_AFTER_LOSSES = 3  # Pause after 3 consecutive losses

# === AUTO LEVERAGE SETTINGS ===
USE_AUTO_LEVERAGE = True
DEFAULT_LEVERAGE = 10
ALTSEASON_RISK_BOOST = 1.5  # Multiplier for position size if altseason detected

# === MARKET MODE SETTINGS ===
ENABLE_TREND_FILTERS = True
TREND_MODE = "AUTO"  # AUTO or MANUAL
FORCE_TREND = "UP"  # UP, DOWN or NEUTRAL (used only if AUTO is False)

# === SMART MODULE TOGGLES ===
ENABLE_AI_SIGNAL_MEMORY = True
ENABLE_SMART_EXIT_MANAGER = True
ENABLE_AUTO_REENTRY = True
ENABLE_ALTSEASON_SCANNER = True
ENABLE_SOCIAL_SENTIMENT_SCANNER = True
ENABLE_MACRO_EVENT_FILTER = True
ENABLE_STEALTH_PUMP_DETECTOR = True
ENABLE_NEWS_VOLUME_COMBO = True
ENABLE_DYNAMIC_SCAN_SPEED = True
ENABLE_SPOT_FALLBACK = True
ENABLE_NEW_LISTING_WATCH = True
ENABLE_WHISKER_READER = True  # Detect fakeouts and liquidity grabs

# === NOTIFICATIONS ===
SEND_SIGNAL_ALERTS = True
SEND_TRADE_LOGS = True
SEND_STATUS_REPORTS = True
SEND_MISSED_OPPORTUNITIES = True
SEND_TOP_5_DAILY = True

# === SCAN SETTINGS ===
FULL_COIN_SCAN = True  # Scans all Bybit USDT pairs
SCAN_BATCH_SIZE = 100  # Number of coins scanned per async cycle

# === TELEGRAM COMMAND SETTINGS ===
ENABLE_TELEGRAM_COMMANDS = True
ENABLE_PORTFOLIO_COMMAND = True
ENABLE_WATCHLIST_COMMANDS = True
ENABLE_PAUSE_RESUME_COMMANDS = True
ENABLE_STATUS_COMMAND = True
ENABLE_ALERT_COMMAND = True

# === EXIT MANAGEMENT ===
USE_TRAILING_STOP = True
TRAILING_STOP_TRIGGER = 1.5  # in %
TRAILING_STOP_DISTANCE = 0.8  # in %

# === AUTO SWITCHING BEHAVIOR ===
AGGRESSIVE_MODE_ENABLED = True
AGGRESSIVE_TRIGGER = {
    "volume_spike": True,
    "altseason_signal": True,
    "meme_hype": True
}

# === TELEGRAM CHANNEL OPTIONS ===
SIGNAL_CHANNEL_NAME = "Live Crypto Sniper"
ASSISTANT_CHANNEL_NAME = "Bot Assistant Logs"

# === DATA RETENTION / LOGGING ===
ENABLE_TRADE_JOURNAL = True
SAVE_TRADE_HISTORY = True
WRITE_LOGS_TO_FILE = True
LOG_FILE_PATH = "logs/bot_activity.log"

# === PERFORMANCE MONITORING ===
ENABLE_DAILY_SUMMARY = True
ENABLE_WEEKLY_REPORT = True
DAILY_SUMMARY_TIME_UTC = "21:00"
