import os
from dotenv import load_dotenv

load_dotenv()

BYBIT_API_KEY = os.getenv("BYBIT_API_KEY")
BYBIT_API_SECRET = os.getenv("BYBIT_API_SECRET")
BYBIT_API_URL = "https://api.bybit.com"


TELEGRAM_BOT_TOKEN = "7803544014:AAGLJVwfTg4Ij5lzI8RIVRfrZkKG9uIZnh4"
TELEGRAM_CHAT_ID = "1806610681"
TELEGRAM_ASSISTANT_CHAT_ID = "-1000000000000" # optional

# === TRADING MODE ===
TRADING_MODE = "auto"  # "auto" or "signal"
RISK_SPOT = 0.02       # default 2% per spot trade
RISK_FUTURES = 0.03    # default 3% per futures trade
DAILY_MAX_LOSS = 0.1   # max daily loss before auto pause (10%)

# === LEVERAGE / MARGIN SETTINGS ===
MARGIN_MODE = "CROSSED"  # or "CROSSED"

# === CANDLE INTERVAL SETTINGS ===
DEFAULT_INTERVAL = '1'
SUPPORTED_INTERVALS = ['1', '3', '5', '15']

# === SIGNAL THRESHOLDS ===
MIN_SCORE_THRESHOLD = 7
ALTSEASON_SCORE_BOOST = 0.5
MEME_SCORE_BOOST = 0.5

# === MEME / ALTSEASON DETECTION ===
ENABLE_MEME_RADAR = True
ENABLE_ALTS_SCALING = True

# === SCAN SPEED CONTROL ===
BASE_SCAN_INTERVAL = 180  # default: 3 minutes
ALTSEASON_SCAN_INTERVAL = 120
MEME_HYPE_SCAN_INTERVAL = 90

# === MARKET TYPES ===
ENABLE_SPOT = True
ENABLE_FUTURES = True

# === SMART SYSTEMS ===
ENABLE_SMART_EXIT = True
ENABLE_AI_SIGNAL_MEMORY = True
ENABLE_LIQUIDITY_TRAP_FILTER = True
ENABLE_WHALE_WATCH = True
ENABLE_NEWS_REACTION = True
